# This package is just there to factorize nushell crates between nix-built plugins

[package]
name = "dummy_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
"nu-protocol" = "0.106.1"
"nu-plugin" = "0.106.1"
