name: nightly-updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  discover-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-branches
        run: |
          echo "branches=$( \
            git ls-remote --heads origin | \
            cut -d/ -f3 | \
            jq -c -R -s '
              split("\n") |
              map(
                select(
                  length > 0 and (startswith("nu") or . == "master")
                )
              )
            '
          )" >> $GITHUB_OUTPUT

  update-branch:
    needs: discover-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.discover-branches.outputs.branches) }}
      fail-fast: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update branch
        run: |
          git config user.name "Nightly updater"
          git config user.email "foo@bar.baz"
          nix flake update --accept-flake-config
          nix run ".#update-plugin-list" --accept-flake-config
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Update ${{ matrix.branch }} branch"
            git push origin HEAD:${{ matrix.branch }}
          else
            echo "No changes on ${{ matrix.branch }}"
          fi
